server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cubesdb
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: VENKY-CUBES